### ISSUE TITLE
 wget https 不支持如何解决的

### ISSUE THREAD

**Issue by phpmaple** [blademainer/miwifi-ss#1]
wget: not an http or ftp url: https://raw.githubusercontent.com/blademainer/miwi                                                                              fi-ss/master/miwifi.sh

**Comment by njwangchuan** [comment]
改用curl下载即可，安装脚本内的wget也要对应修改

**Comment by blademainer** [comment]
@njwangchuan 能提交下PR吗？

**Comment by blademainer** [comment]
@phpmaple 已修改
