### ISSUE TITLE
小米路由器3G，安装成功但翻不了

### ISSUE THREAD

**Issue by glossliu** [blademainer/miwifi-ss#21]
请输入服务器IP:
请输入服务器端口:
请输入密码:
请输入加密方式
aes-256-cfb
refers to not existing zone 'guest'
refers to not existing zone 'guest'
refers to not existing zone 'guest'
 * Flushing IPv4 filter table
 * Flushing IPv4 nat table
 * Flushing IPv4 mangle table
 * Flushing IPv4 raw table
 * Flushing IPv6 filter table
 * Flushing IPv6 mangle table
 * Flushing IPv6 raw table
 * Flushing conntrack table ...
 * Populating IPv4 filter table
   * Zone 'lan'
   * Zone 'wan'
   * Zone 'ready'
   * Rule 'Allow-DHCP-Renew'
   * Rule 'Allow-Ping'
   * Rule 'DHCP for ready'
   * Rule 'DHCP for ready'
   * Rule 'tbus for ready'
   * Rule 'tbus for ready'
   * Rule 'ingress port for PT download'
   * Rule 'xunlei wan accept tcp port 1080 4662 2080 2062'
   * Rule 'xunlei wan accept udp port 4661 3027 888 666 2037 2061 2048 2066'
   * Rule 'xunlei_port_limit_localhost 9000'
   * Redirect 'nxdomain'
   * Forward 'lan' -> 'wan'
 * Populating IPv4 nat table
   * Zone 'lan'
   * Zone 'wan'
   * Zone 'ready'
   * Redirect 'nxdomain'
 * Populating IPv4 mangle table
   * Zone 'lan'
   * Zone 'wan'
   * Zone 'ready'
 * Populating IPv4 raw table
   * Zone 'lan'
   * Zone 'wan'
   * Zone 'ready'
 * Populating IPv6 filter table
   * Zone 'lan'
   * Zone 'wan'
   * Zone 'ready'
   * Rule 'Allow-DHCPv6'
   * Rule 'Allow-ICMPv6-Input'
   * Rule 'Allow-ICMPv6-Forward'
   * Rule 'DHCP for ready'
   * Rule 'DHCP for ready'
   * Rule 'tbus for ready'
   * Rule 'tbus for ready'
   * Rule 'ingress port for PT download'
   * Rule 'xunlei wan accept tcp port 1080 4662 2080 2062'
   * Rule 'xunlei wan accept udp port 4661 3027 888 666 2037 2061 2048 2066'
   * Rule 'xunlei_port_limit_localhost 9000'
   * Forward 'lan' -> 'wan'
 * Populating IPv6 mangle table
   * Zone 'lan'
   * Zone 'wan'
   * Zone 'ready'
 * Populating IPv6 raw table
   * Zone 'lan'
   * Zone 'wan'
   * Zone 'ready'
 * Set tcp_ecn to off
 * Set tcp_syncookies to on
   ! Unable to write value /proc/sys/net/ipv4/tcp_syncookies: No such file or directory
 * Set tcp_window_scaling to on
 * Running script '/lib/firewall.sysapi.loader webinitrdr'
 * Running script '/lib/firewall.sysapi.loader dnsmiwifi'
 * Running script '/lib/firewall.sysapi.loader macfilter'
 * Running script '/lib/firewall.sysapi.loader miqos'
 * Running script '/lib/firewall.sysapi.loader turbo'
 * Running script '/lib/firewall.sysapi.loader xqfp'
 * Running script '/etc/firewall.user'
 * Running script '/lib/firewall.sysapi.loader dmz_bypass_ctf'
 * Running script '/lib/firewall/rr.load reload'
   ! Failed with exit code 1
 * Running script '/usr/share/miniupnpd/firewall.include'
 * Running script '/lib/firewall.sysapi.loader apk_proxy'
 * Running script '/lib/firewall.sysapi.loader kr_query'

Shadowsocks安装成功！

**Comment by haijohn** [comment]
一样的结果
