### ISSUE TITLE
麻烦给curl加上-k参数

### ISSUE THREAD

**Issue by ericchenkai** [blademainer/miwifi-ss#5]
请给curl加上-k参数，以避免“SSL certificate problem: unable to get local issuer certificate”。
谢谢，脚本很好用。

**Comment by blademainer** [comment]
目前会报错吗？

**Comment by ericchenkai** [comment]
我自己fork了一份，给每个curl加上-k参数之后就没问题了。工作的很好，也很方便。谢谢你！
